-- u598963739_control_panel.employee_info definition

CREATE TABLE `employee_info` (
  `employee_id` varchar(48) NOT NULL COMMENT 'format: emp_chars(36)',
  `first_name` varchar(100) NOT NULL,
  `middle_name` varchar(100) DEFAULT NULL,
  `last_name` varchar(100) NOT NULL,
  `fathers_name` varchar(100) NOT NULL,
  `mothers_name` varchar(100) NOT NULL,
  `mother_last_name` varchar(100) NOT NULL,
  `tax_id` varchar(100) NOT NULL,
  `social_security_number_amka` varchar(100) DEFAULT NULL,
  `date_of_birth` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `date_of_birth_epoch` bigint(20) NOT NULL,
  `company` varchar(100) NOT NULL,
  `position` varchar(100) NOT NULL,
  `phone_number` varchar(20) NOT NULL,
  `work_phone_number` varchar(20) DEFAULT NULL,
  `home_phone_number` varchar(20) DEFAULT NULL,
  `other_phone_number` varchar(20) DEFAULT NULL,
  `email` varchar(256) NOT NULL,
  `work_email` varchar(256) DEFAULT NULL,
  `other_email` varchar(256) DEFAULT NULL,
  `address` varchar(128) NOT NULL,
  `postal_code` varchar(30) NOT NULL,
  `city` varchar(100) NOT NULL,
  `notes` longtext DEFAULT NULL,
  `facebook_url` varchar(256) DEFAULT NULL,
  `instagram_url` varchar(256) DEFAULT NULL,
  `linkedin_url` varchar(256) DEFAULT NULL,
  `messenger_url` varchar(256) DEFAULT NULL,
  `whatsup_url` varchar(256) DEFAULT NULL,
  `telegram_url` varchar(256) DEFAULT NULL,
  `viber_url` varchar(256) DEFAULT NULL,
  `status` varchar(30) NOT NULL DEFAULT 'active_full_time' COMMENT 'in (''active_full_time'', ''active_part_time'', ''inactive'', ''on_leave_paid'', ''on_leave_unpaid'', ''fired'', ''resigned'')',
  `start_at` date NOT NULL,
  `end_at` date DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `connected_account_id` varchar(48) NOT NULL,
  PRIMARY KEY (`employee_id`),
  KEY `emplyee_info_FK` (`connected_account_id`),
  CONSTRAINT `emplyee_info_FK` FOREIGN KEY (`connected_account_id`) REFERENCES `accounts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `emplyee_info_CHECK` CHECK (`status` in ('active_full_time','active_part_time','inactive','on_leave_paid','on_leave_unpaid','fired','resigned'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='This table saves the basic info and data for the emplyees';