-- u598963739_control_panel.orders definition

CREATE TABLE `orders` (
  `order_id` varchar(48) NOT NULL,
  `proof` varchar(32) NOT NULL,
  `email` varchar(256) NOT NULL,
  `first_name` varchar(128) NOT NULL,
  `last_name` varchar(128) NOT NULL,
  `address` varchar(128) NOT NULL,
  `postal_code` varchar(20) NOT NULL,
  `city` varchar(128) NOT NULL,
  `country` varchar(128) NOT NULL,
  `phone` varchar(128) NOT NULL,
  `cell_phone` varchar(128) DEFAULT NULL,
  `confirm_date` timestamp NOT NULL DEFAULT current_timestamp(),
  `sent_date` timestamp NULL DEFAULT current_timestamp(),
  `completed_date` timestamp NULL DEFAULT current_timestamp(),
  `confirmed` tinyint(1) NOT NULL DEFAULT 1,
  `sent` tinyint(1) NOT NULL DEFAULT 0,
  `completed` tinyint(1) NOT NULL DEFAULT 0,
  `returned` tinyint(1) NOT NULL DEFAULT 0,
  `transfer_courier` varchar(48) NOT NULL,
  `current_status` varchar(48) NOT NULL DEFAULT 'confirmed',
  `invoice_data__first_name` varchar(128) DEFAULT NULL,
  `invoice_data__last_name` varchar(128) DEFAULT NULL,
  `invoice_data__company` varchar(128) DEFAULT NULL,
  `invoice_data__tax_number` varchar(32) DEFAULT NULL,
  `invoice_data__doy` varchar(128) DEFAULT NULL,
  `invoice_data__address` varchar(128) DEFAULT NULL,
  `invoice_data__postal_code` varchar(20) DEFAULT NULL,
  `invoice_data__city` varchar(128) DEFAULT NULL,
  `invoice_data__country` varchar(128) DEFAULT NULL,
  `invoice_data__phone` varchar(20) DEFAULT NULL,
  `invoice_data__cell_phone` varchar(20) DEFAULT NULL,
  `invoice_data__is_valid` tinyint(1) DEFAULT 1,
  `payment_type` varchar(48) NOT NULL,
  `connected_account_id` varchar(48) NOT NULL,
  `order_number` varchar(32) NOT NULL,
  `invoice_data__invoice_number` varchar(100) NOT NULL,
  `archived` tinyint(1) NOT NULL DEFAULT 0,
  `clear_value` float NOT NULL DEFAULT 0,
  `transportation` float DEFAULT 0,
  `cash_on_delivery_payment` tinyint(1) NOT NULL DEFAULT 0,
  `cash_on_delivery` float NOT NULL DEFAULT 0,
  `extra_fees` tinyint(1) NOT NULL DEFAULT 0,
  `extra_fees_costs` float DEFAULT 0,
  `fees` float NOT NULL DEFAULT 0,
  `fee_percent` float NOT NULL DEFAULT 24,
  `order_total` float NOT NULL DEFAULT 0,
  `tracking_number` varchar(64) DEFAULT NULL,
  `tracking_url` mediumtext DEFAULT NULL,
  `archived_date` timestamp NULL DEFAULT NULL,
  `returned_date` timestamp NULL DEFAULT NULL,
  `notes` mediumtext DEFAULT NULL,
  PRIMARY KEY (`order_id`),
  KEY `orders_FK` (`connected_account_id`),
  KEY `orders_FK_2` (`transfer_courier`),
  KEY `orders_FK_3` (`payment_type`),
  CONSTRAINT `orders_FK` FOREIGN KEY (`connected_account_id`) REFERENCES `accounts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `orders_FK_1` FOREIGN KEY (`payment_type`) REFERENCES `order_payment_types` (`rec_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `orders_FK_2` FOREIGN KEY (`transfer_courier`) REFERENCES `transfer_couriers` (`rec_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `orders_FK_3` FOREIGN KEY (`payment_type`) REFERENCES `order_payment_types` (`rec_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `orders_CHECK` CHECK (`proof` in ('receipt','invoice')),
  CONSTRAINT `orders_CHECK_status` CHECK (`current_status` in ('confirmed','sent','completed','archived','returned'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='This table is used to save the orders from the e-shops etc';