-- u598963739_control_panel.products_update_history definition

CREATE TABLE `products_update_history` (
  `rec_id` varchar(48) NOT NULL,
  `version` varchar(100) NOT NULL DEFAULT 'v0.0',
  `product_id` varchar(48) NOT NULL,
  `headline` varchar(256) NOT NULL,
  `product_brand` varchar(48) NOT NULL,
  `categories_belongs` longtext NOT NULL,
  `product_code` varchar(48) NOT NULL,
  `product_model` varchar(256) NOT NULL,
  `stock` int(11) NOT NULL,
  `supplied_price` float NOT NULL,
  `clear_price` float NOT NULL,
  `fee_percent` float NOT NULL,
  `fees` float NOT NULL,
  `discount_percent` float NOT NULL DEFAULT 0,
  `discount` float NOT NULL DEFAULT 0,
  `specification` longtext NOT NULL,
  `product_description` mediumtext NOT NULL,
  `supplier` varchar(128) NOT NULL,
  `current_status` varchar(128) NOT NULL,
  `archived` tinyint(4) NOT NULL,
  `notes` mediumtext NOT NULL,
  `connected_account_id` varchar(48) NOT NULL,
  `created_at_epoch` bigint(20) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `current_version` varchar(100) NOT NULL,
  `version__created_at_epoch` bigint(20) NOT NULL,
  `version__created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  KEY `products_update_history_FK` (`product_id`),
  KEY `products_update_history_FK_1` (`connected_account_id`),
  CONSTRAINT `products_update_history_FK` FOREIGN KEY (`product_id`) REFERENCES `products` (`product_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `products_update_history_FK_1` FOREIGN KEY (`connected_account_id`) REFERENCES `accounts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='In this table we save the update history of the products.';