-- u598963739_control_panel.products_transactions definition

CREATE TABLE `products_transactions` (
  `rec_id` int(11) NOT NULL AUTO_INCREMENT,
  `product_id` varchar(48) NOT NULL,
  `connected_account_id` varchar(48) NOT NULL,
  `updated_by` varchar(48) NOT NULL,
  `product_created_at` timestamp NULL DEFAULT NULL,
  `whole_product_update` tinyint(1) NOT NULL DEFAULT 0,
  `product_update_categories` tinyint(1) NOT NULL,
  `added_category` varchar(100) DEFAULT '0',
  `removed_category` varchar(100) DEFAULT NULL,
  `product_update_images` tinyint(1) NOT NULL DEFAULT 0,
  `field_changed` varchar(254) DEFAULT NULL,
  `value_before` longtext DEFAULT NULL,
  `value_after` longtext DEFAULT NULL,
  `quantity_sold` int(11) DEFAULT NULL,
  `quantity_added` int(11) DEFAULT NULL,
  `quantity_removed` int(11) DEFAULT NULL,
  `warehouse_id` varchar(48) DEFAULT NULL,
  `runway_id` varchar(48) DEFAULT NULL,
  `column_id` varchar(48) DEFAULT NULL,
  `column_shelf_id` varchar(48) DEFAULT NULL,
  `purchased_price` float DEFAULT NULL,
  `status_changed` tinyint(1) NOT NULL DEFAULT 0,
  `status_before` varchar(100) DEFAULT NULL,
  `status_after` varchar(100) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`rec_id`),
  KEY `products_transactions_FK` (`connected_account_id`),
  KEY `products_transactions_FK_1` (`product_id`),
  KEY `products_transactions_company_warehouses__runways_FK` (`runway_id`),
  KEY `products_transactions_company_warehouses__columns_FK` (`column_id`),
  KEY `products_transactions_company_warehouses__column_shelfs_FK` (`column_shelf_id`),
  CONSTRAINT `products_transactions_FK` FOREIGN KEY (`connected_account_id`) REFERENCES `accounts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `products_transactions_FK_1` FOREIGN KEY (`product_id`) REFERENCES `products` (`product_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=20 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='This table saves all the changed that be made on a product';